=== alphaomegaintegration/user-context-service/target/classes/generator-schemas/Context.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "contextId",
	"contextName",
    "description",
    "permissions",
    "roles"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
	"contextId": {
	  "type": "string"
	},
    "contextName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "permissions": {
      "type": "array",
      "items": {
        "type": "string"
      },
	  "minItems": 1,
	  "uniqueItems": true
    },
    "roles": {
      "type": "array",
      "items": {
        "$ref": "Role.json"
      },
	  "minItems": 1
	},
    "enabled": {
      "type": "boolean"
    },
	"transactionId": {
	  "type": "string"
	},
	"createdBy": {
	  "type": "string"
	},
	"modifiedBy": {
	  "type": "string"
	},
	"createdTime": {
	  "type": "string"
	},
	"modifiedTime": {
	  "type": "string"
	}
  }
}

=== alphaomegaintegration/user-context-service/src/test/resources/contexts/user-context-service.json
{
  "id": "user-context-service",
  "contextId": "user-context-service",
  "contextName": "user-context-service",
  "description": "The context for user-context-service",
  "enabled": true,
  "permissions": [
    "CREATE_CONTEXTS",
    "UPDATE_CONTEXTS",
    "LIST_CONTEXTS",
    "DELETE_CONTEXTS",
    "CREATE_USER_CONTEXTS",
    "UPDATE_USER_CONTEXTS",
    "LIST_USER_CONTEXTS",
    "DELETE_USER_CONTEXTS",
    "LIST_USERS",
    "CREATE_USERS",
    "UPDATE_USERS",
    "DELETE_USERS",
    "VIEW_CONFIGURATIONS",
    "NONE"
  ],
  "roles": [
    {
      "roleId": "admin-user-context-service",
      "roleName": "admin-user-context-service",
      "permissions": [
        "CREATE_CONTEXTS",
        "UPDATE_CONTEXTS",
        "LIST_CONTEXTS",
        "DELETE_CONTEXTS",
        "CREATE_USER_CONTEXTS",
        "UPDATE_USER_CONTEXTS",
        "LIST_USER_CONTEXTS",
        "DELETE_USER_CONTEXTS",
        "LIST_USERS",
        "CREATE_USERS",
        "UPDATE_USERS",
        "DELETE_USERS",
        "VIEW_CONFIGURATIONS"
      ]
    },
    {
      "roleId": "reader-user-context-service",
      "roleName": "reader-user-context-service",
      "permissions": [
        "LIST_CONTEXTS",
        "LIST_USER_CONTEXTS",
        "LIST_USERS"
      ]
    },
    {
      "roleId": "noop-user-context-service",
      "roleName": "noop-user-context-service",
      "permissions": [
        "NONE"
      ]
    }
  ]
}

=== alphaomegaintegration/user-context-service/src/test/resources/contexts/unhrc-bims-context.json
{
  "id": "unhrc-bims",
  "contextId": "unhrc-bims",
  "contextName": "unhrc-bims",
  "description": "The context for unhrc-bims",
  "enabled": true,
  "permissions": [
    "SCHEDULE_APPLICANTS",
    "ASSIGN_ADMIN_ROLE",
    "ASSIGN_ADJUDICATOR_ROLE",
    "LIST_APPLICANTS",
    "BATCH_SCHEDULE_APPLICANTS",
    "VIEW_APPLICANT_DATA",
    "VIEW_MY_SCHEDULE",
    "VIEW_APPLICANT_SCHEDULE",
    "LIST_APPLICANTS_SCHEDULE",
    "LIST_COUNTRIES",
    "LIST_OFFICES",
    "VIEW_COUNTRY_DATA",
    "VIEW_OFFICE_DATA",
    "NONE"
  ],
  "roles": [
    {
      "roleId": "admin-unhrc-bims",
      "roleName": "admin-unhrc-bims",
      "permissions": [
        "SCHEDULE_APPLICANTS",
        "ASSIGN_ADMIN_ROLE",
        "ASSIGN_ADJUDICATOR_ROLE",
        "LIST_APPLICANTS",
        "BATCH_SCHEDULE_APPLICANTS",
        "VIEW_APPLICANT_DATA",
        "VIEW_MY_SCHEDULE",
        "VIEW_APPLICANT_SCHEDULE",
        "LIST_APPLICANTS_SCHEDULE",
        "LIST_COUNTRIES",
        "LIST_OFFICES",
        "VIEW_COUNTRY_DATA",
        "VIEW_OFFICE_DATA"
      ]
    },
    {
      "roleId": "adjudicator-unhrc-bims",
      "roleName": "adjudicator-unhrc-bims",
      "permissions": [
        "VIEW_MY_SCHEDULE"
      ]
    },
    {
      "roleId": "employee-unhrc-bims",
      "roleName": "employee-unhrc-bims",
      "permissions": [
        "SCHEDULE_APPLICANTS",
        "LIST_APPLICANTS",
        "VIEW_APPLICANT_DATA",
        "VIEW_APPLICANT_SCHEDULE"
      ]
    },
    {
      "roleId": "noop-unhrc-bims",
      "roleName": "noop-unhrc-bims",
      "permissions": [
        "NONE"
      ]
    }
  ]
}

=== alphaomegaintegration/user-context-service/src/test/resources/contexts/test-context.json
{
  "id": "testing",
  "contextId": "testing",
  "contextName": "testing",
  "description": "The context for testing",
  "enabled": true,
  "permissions": ["NONE","ALL"],
  "roles": [

    {
      "roleId": "testing-none",
      "roleName": "testing-none",
      "permissions": ["NONE"]
    },
    {
      "roleId": "testing-all",
      "roleName": "testing-all",
      "permissions": ["ALL"]
    }
  ]
}

=== alphaomegaintegration/user-context-service/src/test/resources/contexts/health-context.json
{
  "id": "health",
  "contextId": "health",
  "contextName": "health",
  "description": "The context for health",
  "enabled": true,
  "permissions": ["UP","DOWN","UNKNOWN","NONE"],
  "roles": [

    {
      "roleId": "health-none",
      "roleName": "health-none",
      "permissions": ["NONE"]
    },
    {
      "roleId": "health-admin",
      "roleName": "health-admin",
      "permissions": ["UP","DOWN","UNKNOWN"]
    }
  ]
}
